routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'RosterController@index');

Route::resource('roster','RosterController');
Route::resource('faction','FactionController');

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

app/Http/Controllers/FactionController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Roster;
use App\Faction;
use Illuminate\Http\Request;

class FactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $faction = Faction::orderBy('name')->get();

        return view('pages.faction.index', compact('faction'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.faction.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->file('image') != ''){
            $request->validate([
                'name'        => 'required',
                'description' => 'required',
                'image'       => 'image|mimes:jpeg,png,jpg,gif,svg',
            ]);

            $image = time().'.'.$request->image->extension();  
            $request->image->move(public_path('images'), $image);
            $image = 'images/'.$image;
        } else {
            $request->validate([
                'name'        => 'required',
                'description' => 'required',
            ]);

            $image = 'images/default-faction.jpg';
        }

        $name_id = str_replace(' ', '-', strtolower($request->name));

        $faction_data = array(
            'name'             => $request->name,
            'description'      => $request->description,
            'finisher'         => $request->finisher,
            'signature_move'   => $request->signature_move,
            'social_facebook'  => $request->social_facebook,
            'social_instagram' => $request->social_instagram,
            'social_twitter'   => $request->social_twitter,
            'name_id'          => $name_id,
            'image'            => $image,
        );

        Faction::create($faction_data);

        return redirect()->route('faction.index')->with('success', 'Faction created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Faction  $faction
     * @return \Illuminate\Http\Response
     */
    public function show($name)
    {
        $profile = Faction::where('name_id', $name)->get()->first();

        return view('pages.faction.profile', compact('profile'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Faction  $faction
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $profile = Faction::findOrFail($id);

        return view('pages.faction.edit', compact('profile'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Faction  $faction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->file('image') != ''){
            $request->validate([
                'name'        => 'required',
                'description' => 'required',
                'image'       => 'image|mimes:jpeg,png,jpg,gif,svg',
            ]);

            $image = time().'.'.$request->image->extension();  
            $request->image->move(public_path('images'), $image);
            $image = 'images/'.$image;
        } else {
            $request->validate([
                'name'        => 'required',
                'description' => 'required',
            ]);
        }

        $name_id = str_replace(' ', '-', strtolower($request->name));

        $faction_data = array(
            'name'             => $request->name,
            'description'      => $request->description,
            'finisher'         => $request->finisher,
            'signature_move'   => $request->signature_move,
            'social_facebook'  => $request->social_facebook,
            'social_instagram' => $request->social_instagram,
            'social_twitter'   => $request->social_twitter,
            'name_id'          => $name_id,
        );

        if($request->file('image') != '') { $faction_data['image'] = $image; }

        Faction::whereId($id)->update($faction_data);

        return redirect()->route('faction.show', $name_id)->with('success', 'Faction updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Faction  $faction
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $profile = Faction::findOrFail($id);
        $profile->delete();

        return redirect()->route('faction.index')->with('success', 'Faction deleted successfully!');
    }
}

resources/views/pages/faction/create.blade.php
@extends('layouts.master')

@section('pageTitle', 'Create Faction')

@section('content')
    <form class="form-row" action="{{ route('faction.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="col-12">
            <div class="card card-mwf-img card-mwf-faction">
                <img class="card-img" src="{{ asset('images/default-faction.jpg') }}">
            </div>
            <div class="custom-file my-3">
                <label for="image" class="custom-file-label">
                    <h4>
                        {{ __('Upload Image') }}
                    </h4>
                </label>
                <input type="file" name="image" class="custom-file-input" id="image" accept="image/*">
                @error('image')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
        <div class="col-12 font-montserrat">
            <div class="card card-mwf-text">
                <div class="card-body">
                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">
                            <h1>
                                {{ __('Name:') }}
                            </h1>
                        </label>
                        <div class="col-sm-10">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="description" class="col-sm-2 col-form-label">
                            <p>
                                {{ __('Description:') }}
                            </p>
                        </label>
                        <div class="col-sm-10">
                            <textarea id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ old('description') }}" required autocomplete="description">
                            </textarea>
                            @error('description')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <div class="col-12">
                            <label for="finisher" class="col-sm-2 col-form-label">
                                <strong>{{ __('Finisher:') }}</stromg>
                            </label>
                            <div class="col-sm-10">
                                <input id="finisher" type="text" class="form-control @error('finisher') is-invalid @enderror" name="finisher" value="{{ old('finisher') }}" autocomplete="finisher">
                                @error('finisher')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-12">
                            <label for="signature_move" class="col-sm-2 col-form-label">
                                <strong>{{ __('Signature Move:') }}</stromg>
                            </label>
                            <div class="col-sm-10">
                                <input id="signature_move" type="text" class="form-control @error('signature_move') is-invalid @enderror" name="signature_move" value="{{ old('signature_move') }}" autocomplete="signature_move">
                                @error('signature_move')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <button class="btn btn-lg btn-block btn-outline-success" type="submit">
                Create Faction
            </button>
        </div>
    </form>
@endsection

resources/views/pages/faction/edit.blade.php
@extends('layouts.master')

@section('pageTitle', 'Edit Faction')

@section('content')
    <form class="form-row" action="{{ route('faction.update', $profile->id) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('PATCH')
        <div class="col-12">
            <div class="card card-mwf-img card-mwf-faction">
                <img class="card-img" src="{{ asset($profile->image) }}">
            </div>
            <div class="custom-file my-3">
                <label for="image" class="custom-file-label">
                    <h4>
                        {{ __('Upload Image') }}
                    </h4>
                </label>
                <input type="file" name="image" class="custom-file-input" id="image" accept="image/*">
                @error('image')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
        <div class="col-12 font-montserrat">
            <div class="card card-mwf-text">
                <div class="card-body">
                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">
                            <h1>
                                {{ __('Name:') }}
                            </h1>
                        </label>
                        <div class="col-sm-10">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $profile->name }}" required autocomplete="name" autofocus>
                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="description" class="col-sm-2 col-form-label">
                            <p>
                                {{ __('Description:') }}
                            </p>
                        </label>
                        <div class="col-sm-10">
                            <textarea id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ $profile->description }}" required autocomplete="description">{{ $profile->description }}</textarea>
                            @error('description')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <div class="col-12">
                            <label for="finisher" class="col-sm-2 col-form-label">
                                <strong>{{ __('Finisher:') }}</stromg>
                            </label>
                            <div class="col-sm-10">
                                <input id="finisher" type="text" class="form-control @error('finisher') is-invalid @enderror" name="finisher" value="{{ $profile->finisher }}" autocomplete="finisher">
                                @error('finisher')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-12">
                            <label for="signature_move" class="col-sm-2 col-form-label">
                                <strong>{{ __('Signature Move:') }}</stromg>
                            </label>
                            <div class="col-sm-10">
                                <input id="signature_move" type="text" class="form-control @error('signature_move') is-invalid @enderror" name="signature_move" value="{{ $profile->signature_move }}" autocomplete="signature_move">
                                @error('signature_move')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <button class="btn btn-lg btn-block btn-outline-success" type="submit">
                Update Faction
            </button>
        </div>
    </form>
@endsection

resources/views/pages/faction/index.blade.php
@extends('layouts.master')

@section('pageTitle', 'Factions')

@section('content')
    @foreach($faction as $profile)
        <div class="col-12 col-md-6 my-2">
            <a class="card card-mwf-img card-mwf-faction" href="{{ route('faction.show', $profile->name_id) }}">
                <img class="card-img" src="{{ asset($profile->image) }}" alt="{{ $profile->name }}">
                <div class="card-img-overlay text-center">
                    <h2 class="card-title position-relative">
                        {{ $profile->name }}
                    </h2>
                </div>
            </a>
        </div>
    @endforeach
@endsection

resources/views/pages/faction/profile.blade.php
@extends('layouts.master')

@section('pageTitle', 'Faction - ' . $profile->name)

@section('content')
    <div class="col-12">
        <h4 class="card-title text-center d-md-none">
            {{ $profile->name }}
        </h4>
        <div class="card card-mwf-img card-mwf-faction">
            <img class="card-img" src="{{ asset($profile->image) }}" alt="{{ $profile->name }}">
            <div class="card-img-overlay text-center d-sm-none d-md-block">
                <h1 class="card-title position-relative">
                    {{ $profile->name }}
                </h1>
            </div>
        </div>
    </div>
    <div class="col-12 font-montserrat">
        <div class="card card-mwf-text">
            <div class="card-body">
                <h1 class="card-title">
                    {{ $profile->name }}
                </h1>
                <p class="card-description">
                    <em>{{ $profile->description }}</em>
                </p>

                @if( $profile->finisher != NULL )
                    <p class="card-text card-mwf-text-label">
                        <strong>Finisher:</strong>
                    </p>
                    <p class="card-text card-mwf-text-value">
                        {{ $profile->finisher }}
                    </p>
                @endif

                @if( $profile->signature_move != NULL )
                    <p class="card-text card-mwf-text-label">
                        <strong>Signature Move:</strong>
                    </p>
                    <p class="card-text card-mwf-text-value">
                        {{ $profile->signature_move }}
                    </p>
                @endif
                
                <div class="row">
                    @foreach ($profile->rosters as $roster)
                        <div class="col-12 col-md-3 my-2">
                            <a class="card card-mwf-img card-mwf-roster" href="{{ route('roster.show', $roster->name_id) }}">
                                <img class="card-img" src="{{ asset($roster->image) }}" alt="{{ $roster->name }}">
                                <div class="card-img-overlay">
                                    <h2 class="card-title">
                                        {{ $roster->name }}
                                    </h2>
                                </div>
                            </a>
                            <h4 class="d-md-none mt-2">
                                {{ $roster->name }}
                            </h4>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection