routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'RosterController@index');

Route::resource('roster','RosterController');
Route::resource('faction','FactionController');

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

app/Roster.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Roster extends Model
{
    protected $fillable = ['name', 'name_id', 'alias', 'description', 'height', 'weight', 'hometown', 'image', 'champion_image', 'finisher', 'signature_move', 'social_facebook','social_instagram', 'social_twitter', 'is_active', 'faction_id', 'type_id'];

    public function faction()
    {
        return $this->belongsTo('App\Faction');
    }
}

app/Http/Controllers/RosterController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Roster;
use App\Faction;
use Illuminate\Http\Request;

class RosterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roster = Roster::orderBy('name')->get();

        return view('pages.roster.index', compact('roster'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['factions'] = Faction::all();

        return view('pages.roster.create', compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->file('image') != ''){
            $request->validate([
                'name'        => 'required',
                'description' => 'required',
                'height'      => 'required',
                'weight'      => 'required',
                'hometown'    => 'required',
                'image'       => 'image|mimes:jpeg,png,jpg,gif,svg',
            ]);

            $image = time().'.'.$request->image->extension();  
            $request->image->move(public_path('images'), $image);
            $image = 'images/'.$image;
        } else {
            $request->validate([
                'name'        => 'required',
                'description' => 'required',
                'height'      => 'required',
                'weight'      => 'required',
                'hometown'    => 'required',
            ]);

            $image = 'images/default-roster.jpg';
        }

        if ($request->faction_id == 0) {
            $faction_id = NULL;
        } else {
            $faction_id = $request->faction_id;
        }

        $name_id = str_replace(' ', '-', strtolower($request->name));

        $roster_data = array(
            'name'             => $request->name,
            'alias'            => $request->alias,
            'description'      => $request->description,
            'height'           => $request->height,
            'weight'           => $request->weight,
            'hometown'         => $request->hometown,
            'finisher'         => $request->finisher,
            'signature_move'   => $request->signature_move,
            'social_facebook'  => $request->social_facebook,
            'social_instagram' => $request->social_instagram,
            'social_twitter'   => $request->social_twitter,
            'faction_id'       => $faction_id,
            'name_id'          => $name_id,
            'image'            => $image,
        );

        Roster::create($roster_data);

        return redirect()->route('roster.index')->with('success', 'Profile created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Roster  $roster
     * @return \Illuminate\Http\Response
     */
    public function show($name)
    {
        $profile = Roster::where('name_id', $name)->get()->first();

        return view('pages.roster.profile', compact('profile'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Roster  $roster
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['factions'] = Faction::all();
        $profile = Roster::findOrFail($id);

        return view('pages.roster.edit', compact('profile', 'data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Roster  $roster
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->file('image') != ''){
            $request->validate([
                'name'        => 'required',
                'description' => 'required',
                'height'      => 'required',
                'weight'      => 'required',
                'hometown'    => 'required',
                'image'       => 'image|mimes:jpeg,png,jpg,gif,svg',
            ]);

            $image = time().'.'.$request->image->extension();  
            $request->image->move(public_path('images'), $image);
            $image = 'images/'.$image;
        } else {
            $request->validate([
                'name'        => 'required',
                'description' => 'required',
                'height'      => 'required',
                'weight'      => 'required',
                'hometown'    => 'required',
            ]);
        }

        if ($request->faction_id == 0) {
            $faction_id = NULL;
        } else {
            $faction_id = $request->faction_id;
        }

        $name_id = str_replace(' ', '-', strtolower($request->name));

        $roster_data = array(
            'name'             => $request->name,
            'alias'            => $request->alias,
            'description'      => $request->description,
            'height'           => $request->height,
            'weight'           => $request->weight,
            'hometown'         => $request->hometown,
            'finisher'         => $request->finisher,
            'signature_move'   => $request->signature_move,
            'social_facebook'  => $request->social_facebook,
            'social_instagram' => $request->social_instagram,
            'social_twitter'   => $request->social_twitter,
            'faction_id'       => $faction_id,
            'name_id'          => $name_id,
        );

        if($request->file('image') != '') { $roster_data['image'] = $image; }

        Roster::whereId($id)->update($roster_data);

        return redirect()->route('roster.show', $name_id)->with('success', 'Profile updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Roster  $roster
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $profile = Roster::findOrFail($id);
        $profile->delete();

        return redirect()->route('roster.index')->with('success', 'Profile deleted successfully!');
    }
}

resources/views/pages/roster/create.blade.php
@extends('layouts.master')

@section('pageTitle', 'Create Profile')

@section('content')
    <form class="form-row" action="{{ route('roster.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="col-12 col-md-3">
            <div class="card card-mwf-img">
                <img class="card-img" src="{{ asset('images/default-roster.jpg') }}">
            </div>
            <div class="custom-file my-3">
                <label for="image" class="custom-file-label">
                    <h4>
                        {{ __('Upload Image') }}
                    </h4>
                </label>
                <input type="file" name="image" class="custom-file-input" id="image" accept="image/*">
                @error('image')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
        <div class="col-12 col-md-9 font-montserrat">
            <div class="card card-mwf-text">
                <div class="card-body">
                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">
                            <h1>
                                {{ __('Name:') }}
                            </h1>
                        </label>
                        <div class="col-sm-10">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="alias" class="col-sm-2 col-form-label">
                            <h4 class="text-muted">
                                {{ __('Alias:') }}
                            </h4>
                        </label>
                        <div class="col-sm-10">
                            <input id="alias" type="text" class="form-control @error('alias') is-invalid @enderror" name="alias" value="{{ old('alias') }}" autocomplete="alias">
                            @error('alias')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="description" class="col-sm-2 col-form-label">
                            <p>
                                {{ __('Description:') }}
                            </p>
                        </label>
                        <div class="col-sm-10">
                            <textarea id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ old('description') }}" required autocomplete="description">
                            </textarea>
                            @error('description')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <div class="col-12 col-lg-6">
                            <label for="hometown" class="col-form-label">
                                <strong>{{ __('Hometown:') }}</stromg>
                            </label>
                            <input id="hometown" type="text" class="form-control @error('hometown') is-invalid @enderror" name="hometown" value="{{ old('hometown') }}" required autocomplete="hometown">
                            @error('hometown')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-12 col-lg-3">
                            <label for="height" class="col-form-label">
                                <strong>{{ __('Height:') }}</stromg>
                            </label>
                            <input id="height" type="text" class="form-control @error('height') is-invalid @enderror" name="height" value="{{ old('height') }}" required autocomplete="height">
                            @error('height')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-12 col-lg-3">
                            <label for="weight" class="col-form-label">
                                <strong>{{ __('Weight:') }}</stromg>
                            </label>
                            <input id="weight" type="text" class="form-control @error('weight') is-invalid @enderror" name="weight" value="{{ old('weight') }}" required autocomplete="weight">
                            @error('weight')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <div class="col-12">
                            <label for="finisher" class="col-sm-2 col-form-label">
                                <strong>{{ __('Finisher:') }}</stromg>
                            </label>
                            <div class="col-sm-10">
                                <input id="finisher" type="text" class="form-control @error('finisher') is-invalid @enderror" name="finisher" value="{{ old('finisher') }}" autocomplete="finisher">
                                @error('finisher')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-12">
                            <label for="signature_move" class="col-sm-2 col-form-label">
                                <strong>{{ __('Signature Move:') }}</stromg>
                            </label>
                            <div class="col-sm-10">
                                <input id="signature_move" type="text" class="form-control @error('signature_move') is-invalid @enderror" name="signature_move" value="{{ old('signature_move') }}" autocomplete="signature_move">
                                @error('signature_move')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <div class="col-12">
                            <label for="faction_id"  class="col-sm-2 col-form-label">
                                <strong>{{ __('Faction:') }}</strong>
                            </label>
                            <div class="col-sm-10">
                                <select name="faction_id" id="faction_id" class="form-control @error('faction_id') is-invalid @enderror" value="{{ old('faction_id') }}" autocomplete="faction_id">
                                    <option value="0">
                                        None
                                    </option>
                                    @foreach ($data['factions'] as $faction)
                                        <option value="{{ $faction->id }}">
                                            {{ $faction->name }}
                                        </option>
                                    @endforeach
                                </select>
                                @error('faction_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <button class="btn btn-lg btn-block btn-outline-success" type="submit">
                Create Profile
            </button>
        </div>
    </form>
@endsection

resources/views/pages/roster/edit.blade.php
@extends('layouts.master')

@section('pageTitle', 'Edit Profile')

@section('content')
    <form class="form-row" action="{{ route('roster.update', $profile->id) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('PATCH')
        <div class="col-12 col-md-3">
            <div class="card card-mwf-img">
                <img class="card-img" src="{{ asset($profile->image) }}">
            </div>
            <div class="custom-file my-3">
                <label for="image" class="custom-file-label">
                    <h4>
                        {{ __('Upload Image') }}
                    </h4>
                </label>
                <input type="file" name="image" class="custom-file-input" id="image" accept="image/*">
                @error('image')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
        <div class="col-12 col-md-9 font-montserrat">
            <div class="card card-mwf-text">
                <div class="card-body">
                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">
                            <h1>
                                {{ __('Name:') }}
                            </h1>
                        </label>
                        <div class="col-sm-10">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $profile->name }}" required autocomplete="name" autofocus>
                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="alias" class="col-sm-2 col-form-label">
                            <h4 class="text-muted">
                                {{ __('Alias:') }}
                            </h4>
                        </label>
                        <div class="col-sm-10">
                            <input id="alias" type="text" class="form-control @error('alias') is-invalid @enderror" name="alias" value="{{ $profile->alias }}" autocomplete="alias">
                            @error('alias')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="description" class="col-sm-2 col-form-label">
                            <p>
                                {{ __('Description:') }}
                            </p>
                        </label>
                        <div class="col-sm-10">
                            <textarea id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ $profile->description }}" required autocomplete="description">{{ $profile->description }}</textarea>
                            @error('description')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <div class="col-12 col-lg-6">
                            <label for="hometown" class="col-form-label">
                                <strong>{{ __('Hometown:') }}</stromg>
                            </label>
                            <input id="hometown" type="text" class="form-control @error('hometown') is-invalid @enderror" name="hometown" value="{{ $profile->hometown }}" required autocomplete="hometown">
                            @error('hometown')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-12 col-lg-3">
                            <label for="height" class="col-form-label">
                                <strong>{{ __('Height:') }}</stromg>
                            </label>
                            <input id="height" type="text" class="form-control @error('height') is-invalid @enderror" name="height" value="{{ $profile->height }}" required autocomplete="height">
                            @error('height')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-12 col-lg-3">
                            <label for="weight" class="col-form-label">
                                <strong>{{ __('Weight:') }}</stromg>
                            </label>
                            <input id="weight" type="text" class="form-control @error('weight') is-invalid @enderror" name="weight" value="{{ $profile->weight }}" required autocomplete="weight">
                            @error('weight')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <div class="col-12">
                            <label for="finisher" class="col-sm-2 col-form-label">
                                <strong>{{ __('Finisher:') }}</stromg>
                            </label>
                            <div class="col-sm-10">
                                <input id="finisher" type="text" class="form-control @error('finisher') is-invalid @enderror" name="finisher" value="{{ $profile->finisher }}" autocomplete="finisher">
                                @error('finisher')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-12">
                            <label for="signature_move" class="col-sm-2 col-form-label">
                                <strong>{{ __('Signature Move:') }}</stromg>
                            </label>
                            <div class="col-sm-10">
                                <input id="signature_move" type="text" class="form-control @error('signature_move') is-invalid @enderror" name="signature_move" value="{{ $profile->signature_move }}" autocomplete="signature_move">
                                @error('signature_move')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <div class="col-12">
                            <label for="faction_id"  class="col-sm-2 col-form-label">
                                <strong>{{ __('Faction:') }}</strong>
                            </label>
                            <div class="col-sm-10">
                                <select name="faction_id" id="faction_id" class="form-control @error('faction_id') is-invalid @enderror" value="{{ $profile->faction_id }}" autocomplete="faction_id">
                                    <option value="0">
                                        None
                                    </option>
                                    @foreach ($data['factions'] as $faction)
                                            <option value="{{ $faction->id }}" @if ($profile->faction_id == $faction->id) selected @endif>
                                                {{ $faction->name }}
                                            </option>
                                        
                                    @endforeach
                                </select>
                                @error('faction_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <button class="btn btn-lg btn-block btn-outline-success" type="submit">
                Update Profile
            </button>
        </div>
    </form>
@endsection

resources/views/pages/roster/index.blade.php
@extends('layouts.master')

@section('pageTitle', 'Roster')

@section('content')
    @foreach($roster as $profile)
        <div class="col-6 col-md-3 my-2">
            <a class="card card-mwf-img card-mwf-roster" href="{{ route('roster.show', $profile->name_id) }}">
                <img class="card-img" src="{{ asset($profile->image) }}" alt="{{ $profile->name }}">
                <div class="card-img-overlay">
                    <h2 class="card-title">
                        {{ $profile->name }}
                    </h2>
                </div>
            </a>
        </div>
    @endforeach
@endsection

resources/views/pages/roster/profile.blade.php
@extends('layouts.master')

@section('pageTitle', 'Profile - ' . $profile->name)

@section('content')
    <div class="col-12 col-md-3">
        <div class="card card-mwf-img">
            <img class="card-img" src="{{ asset($profile->image) }}" alt="{{ $profile->name }}">
            <div class="card-img-overlay">
                <h2 class="card-title">
                    {{ $profile->name }}
                </h2>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-9 font-montserrat">
        <div class="card card-mwf-text">
            <div class="card-body">
                <h1 class="card-title d-sm-none d-md-block">
                    {{ $profile->name }}
                </h1>
                @if( $profile->alias != NULL )
                <h4 class="card-subtitle text-muted">
                    {{ $profile->alias }}
                </h4>
                @endif
                <p class="card-description">
                    <em>{{ $profile->description }}</em>
                </p>

                <div class="border-top my-3"></div>

                <div class="row">
                    <div class="col-12 col-md-4">
                        <p class="card-text card-mwf-text-label">
                            <strong>Hometown:</strong>
                        </p>
                        <p class="card-text card-mwf-text-value">
                            {{ $profile->hometown }}
                        </p>
                    </div>

                    <div class="col-6 col-md-4">
                        <p class="card-text card-mwf-text-label">
                            <strong>Height:</strong>
                        </p>
                        <p class="card-text card-mwf-text-value">
                            {{ $profile->height }}
                        </p>
                    </div>

                    <div class="col-6 col-md-4">
                        <p class="card-text card-mwf-text-label">
                            <strong>Weight:</strong>
                        </p>
                        <p class="card-text card-mwf-text-value">
                            {{ $profile->weight }}
                        </p>
                    </div>
                </div>

                @if( $profile->finisher != NULL )
                    <p class="card-text card-mwf-text-label">
                        <strong>Finisher:</strong>
                    </p>
                    <p class="card-text card-mwf-text-value">
                        {{ $profile->finisher }}
                    </p>
                @endif

                @if( $profile->signature_move != NULL )
                    <p class="card-text card-mwf-text-label">
                        <strong>Signature Move:</strong>
                    </p>
                    <p class="card-text card-mwf-text-value">
                        {{ $profile->signature_move }}
                    </p>
                @endif
                
                @if( $profile->faction != NULL )
                    <p class="card-text card-mwf-text-label">
                        <strong>Faction:</strong>
                    </p>
                    <p class="card-text card-mwf-text-value">
                        <a href="{{ route('faction.show', $profile->faction->name_id) }}">
                            {{ $profile->faction->name }}
                        </a>
                    </p>
                @endif
            </div>
        </div>
    </div>
@endsection